# Generated by Django 5.0.4 on 2024-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
