# Generated by Django 5.0.4 on 2024-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_booking_amount_alter_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(default='No additional notes', null=True),
        ),
    ]
